"""
Turns tools/demo_replies.py into build/gen/demo_data.c + demo_data.h for the
demo ROM. Replies are wrapped and indented by the bridge's own Wrapper, so the
demo shows them exactly as the live bridge would.

Run: python3 tools/gen_demo.py   (make demo does this; needs build/gen/tiles.json)
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "bridge"))
sys.path.insert(0, str(ROOT / "tools"))

import bridge  # noqa: E402
from demo_replies import KEYWORDS, REPLIES  # noqa: E402

GEN = ROOT / "build" / "gen"


def render(text: str) -> list[int]:
    out = bytearray()
    w = bridge.Wrapper(out.extend, bridge.COLS - bridge.CLAUDE_INDENT, bridge.CLAUDE_INDENT, indented=True)
    w.feed(text)
    w.finish()
    assert 0 not in out and 0xFF not in out
    return list(out) + [0]


def c_bytes(data: list[int]) -> str:
    return ",".join(str(b) for b in data)


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    cats = list(REPLIES)
    for need in ("simpler", "more", "fallback"):
        assert need in cats, f"demo_replies.py needs a '{need}' category"
    for kw, cat in KEYWORDS:
        assert cat in cats, f"keyword {kw!r} points at unknown category {cat!r}"

    arrays, texts, simpler, more, first, count = [], [], [], [], [], []
    for cat in cats:
        first.append(len(texts))
        count.append(len(REPLIES[cat]))
        for r in REPLIES[cat]:
            r = {"text": r} if isinstance(r, str) else r
            i = len(texts)
            arrays.append(f"static const uint8_t r{i}[] = {{{c_bytes(render(r['text']))}}};")
            texts.append(f"r{i}")
            for key, lst in (("simpler", simpler), ("more", more)):
                if key in r:
                    arrays.append(f"static const uint8_t r{i}_{key}[] = {{{c_bytes(render(r[key]))}}};")
                    lst.append(f"r{i}_{key}")
                else:
                    lst.append("0")

    defines = "\n".join(f"#define CAT_{c.upper()} {i}u" for i, c in enumerate(cats))
    GEN.mkdir(parents=True, exist_ok=True)
    (GEN / "demo_data.h").write_text(f"""/* generated by tools/gen_demo.py from tools/demo_replies.py, do not edit */
#ifndef DEMO_DATA_H
#define DEMO_DATA_H

#include <stdint.h>

#define DEMO_CATS {len(cats)}u
#define DEMO_KEYWORDS {len(KEYWORDS)}u
{defines}

/* replies: bubble-free byte streams, exactly what the bridge would send */
extern const uint8_t * const demo_text[];
extern const uint8_t * const demo_simpler[];   /* 0 if none */
extern const uint8_t * const demo_more[];
extern const uint8_t demo_cat_first[];
extern const uint8_t demo_cat_count[];
extern const char * const demo_kw[];
extern const uint8_t demo_kw_cat[];

#endif
""")
    (GEN / "demo_data.c").write_text(f"""/* generated by tools/gen_demo.py from tools/demo_replies.py, do not edit */
#include <stdint.h>
#include "demo_data.h"

{chr(10).join(arrays)}

const uint8_t * const demo_text[] = {{ {", ".join(texts)} }};
const uint8_t * const demo_simpler[] = {{ {", ".join(simpler)} }};
const uint8_t * const demo_more[] = {{ {", ".join(more)} }};
const uint8_t demo_cat_first[] = {{ {", ".join(map(str, first))} }};
const uint8_t demo_cat_count[] = {{ {", ".join(map(str, count))} }};
const char * const demo_kw[] = {{ {", ".join(c_str(k) for k, _ in KEYWORDS)} }};
const uint8_t demo_kw_cat[] = {{ {", ".join(str(cats.index(c)) for _, c in KEYWORDS)} }};
""")
    print(f"{len(texts)} demo replies in {len(cats)} categories")


if __name__ == "__main__":
    main()
